services:
  app:
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://dsc:15032002@db:3000/dsc_ebooks
    ports:
      - "3000:3000"

  db:
    image: postgres:16-alpine
    container_name: eq04-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: dsc
      POSTGRES_PASSWORD: dsc_password
      POSTGRES_DB: dsc_ebooks

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
